services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DB_CONNECTION_STR}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    expose:
      - "3000"
    volumes:
      - backend_data:/data
    restart: unless-stopped

  caddy:
    build:
      context: .
      args:
        FRONTEND_BUILD_DIR: dist
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_DO_SSH_HOST: ${VITE_DO_SSH_HOST}
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  backend_data:
  caddy_data:
  caddy_config:
