version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=/data/data.db
    expose:
      - "3000"
    volumes:
      - backend_data:/data
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
      args:
        FRONTEND_BUILD_DIR: dist
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  backend_data:
  caddy_data:
  caddy_config:
