name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    services: &postgres
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: promptswap_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: ./.github/actions/build
        with:
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}

  build-and-deploy:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    services: *postgres
    steps:
      - uses: ./.github/actions/build
        with:
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
      - uses: ./.github/actions/deploy
        with:
          do-ssh-host: ${{ secrets.DO_SSH_HOST }}
          do-ssh-user: ${{ secrets.DO_SSH_USER }}
          do-ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          do-ssh-passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          domain: ${{ secrets.DOMAIN }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          db-connection-str: ${{ secrets.DB_CONNECTION_STR }}
